[una]
repos = confs/repos/llvm-tools.repo confs/repos/build-tools.repo confs/repos/linux-headers.repo confs/repos/musl.repo confs/repos/llvm-runtime.repo \
    confs/repos/busybox.repo confs/repos/openssl.repo confs/repos/nsd.repo confs/repos/mxmux.repo confs/repos/dropbear.repo confs/repos/wireguard-tools.repo confs/repos/libmnl.repo confs/repos/libnftnl.repo confs/repos/nftables.repo confs/repos/linux-image.repo

# etc_dir = skel/etc
# kconfig = confs/kernel.<arch>.config
cpu_flags = -O3 -march=x86-64-v4 -pipe
