[llvm-host]
una_repo = llvm-project.git
repo_dir = repo/llvm
una_file = una/host.py
origin_url = /mnt/work/bld/llvm-project.git
type = host
tag = llvmorg-22.1.4
sparse_ignore_dirs = flang, flang-rt

#[rust]
#una_repo = rust.git
#repo_dir = repo/rust
#una_file = una/una.py
#origin_url = /mnt/work/bld/rust.git
#type = host

[linux-headers]
una_repo = linux.git
repo_dir = repo/kernel
una_file = una/headers.py
origin_url = /mnt/work/bld/linux-stable.git
type = base
tag = v7.0.1
sparse_ignore_dirs = Documentation, arch/arm/boot/dts, arch/arm64/boot/dts

[musl]
una_repo = musl.git
repo_dir = repo/musl
origin_url = /mnt/work/bld/musl.git
tag = v1.2.6
type = base

[llvm-runtime]
ref = llvm-host
una_file = una/runtime.py
type = base

[busybox]
una_repo = busybox.git
repo_dir = repo/busybox
origin_url = /mnt/work/bld/busybox.git
tag = 1_37_0
type = other

[openssl]
una_repo = openssl.git
repo_dir = repo/openssl
origin_url = /mnt/work/bld/openssl.git
tag = openssl-4.0.0
type = other

[nsd]
una_repo = nsd.git
repo_dir = repo/nsd
origin_url = /mnt/work/bld/nsd.git
tag = NSD_4_14_2_REL
type = other

[mxmux]
una_repo = mxmux.git
repo_dir = repo/mxmux
origin_url = /mnt/work/bld/mxmux.git
type = other

[dropbear]
una_repo = dropbear.git
repo_dir = repo/dropbear
origin_url = /mnt/work/bld/dropbear.git
tag = DROPBEAR_2025.89
type = other

[wireguard-tools]
una_repo = wireguard-tools.git
repo_dir = repo/wireguard-tools
origin_url = /mnt/work/bld/wireguard-tools.git
tag = v1.0.20260223
type = other

[libmnl]
una_repo = libmnl.git
repo_dir = repo/libmnl
origin_url = /mnt/work/bld/libmnl.git
tag = libmnl-1.0.5
type = base

[libnftnl]
una_repo = libnftnl.git
repo_dir = repo/libnftnl
origin_url = /mnt/work/bld/libnftnl.git
tag = libnftnl-1.3.1
type = base

[nftables]
una_repo = nftables.git
repo_dir = repo/nftables
origin_url = /mnt/work/bld/nftables.git
tag = v1.1.6
type = other

[linux-image]
ref = linux-headers
una_file = una/kernel.py
type = other
kernel_name = kernel.<arch>
kernel_image.x32 = arch/x86/boot/bzImage
kernel_image.x86_64 = arch/x86/boot/bzImage
kernel_image.aarch64 = arch/arm64/boot/Image.gz
kernel_image.riscv64 = arch/riscv/boot/Image

[una]
# etc_dir = skel/etc
# kconfig = confs/kernel.<arch>.config
cpu_flags = -O3 -march=x86-64-v4 -pipe

