#!/usr/bin/sh
PATH=/usr/sbin:/usr/bin

HUGE_PAGES=",huge=within_size"
SERIAL_CONSOLE_DEV="ttyS0"

case "$(uname -m)" in
    aarch64)
        SERIAL_CONSOLE_DEV=ttyAMA0
        ;;
    riscv64)
        HUGE_PAGES=
        ;;
esac

mkdir new_root
mount -n -t tmpfs -o size=64M,nodev,nosuid,noatime,nodiratime,rw"${HUGE_PAGES}" rootfs new_root
cp -a $(find / -maxdepth 1 \( -type d -o -type l \) ! -name / ! -name new_root -print) new_root
sed -e s:@SERIAL_CONSOLE_DEVICE@:${SERIAL_CONSOLE_DEV}: -i new_root/etc/inittab
rm -f new_root/dev/console

mkdir new_root/boot
mkdir new_root/data
rm new_root/etc/rdinit

mount -n -t proc -o rw,nosuid,nodev,noexec,relatime proc proc
mount -n -o remount,ro /new_root
umount proc

mount -n -t proc -o rw,nosuid,nodev,noexec,relatime proc new_root/proc
mount -n -t sysfs -o rw,nosuid,nodev,noexec,relatime sysfs new_root/sys
mount -n -t devtmpfs -o noexec,relatime,nosuid,mode=0755,size=1M"${HUGE_PAGES}" devtmpfs new_root/dev
mkdir new_root/dev/pts
mount -n -t devpts -o noexec,noatime,nodiratime,nosuid,mode=620,gid=0,ptmxmode=0666 devpts new_root/dev/pts
mount -n -t tmpfs -o noexec,nodev,nosuid,noatime,nodiratime,nosuid,mode=1777,size=16M"${HUGE_PAGES}" tmpfs new_root/run
mount -n -t tmpfs -o noexec,nodev,nosuid,noatime,nodiratime,nosuid,mode=1777,size=16M"${HUGE_PAGES}" tmpfs new_root/tmp
ln -sf ../proc/self/fd new_root/dev/fd
ln -sf ../proc/self/fd/0 new_root/dev/stdin
ln -sf ../proc/self/fd/1 new_root/dev/stdout
ln -sf ../proc/self/fd/2 new_root/dev/stderr
ln -sf usr/sbin/init /init

exec switch_root -c /dev/console new_root /usr/sbin/init
