flush ruleset
table ip filter {
    chain FORWARD {
        type filter hook forward priority filter; policy drop;
        jump protos_check
        ct state established accept
        ct state related accept
        jump forward_filter
        log prefix "F "
    }

    chain INPUT {
        type filter hook input priority filter; policy drop;
        jump protos_check
        iifname "eth0" udp dport 51820 accept
        ct state established accept
        ct state related accept
        jump input_filter
        log prefix "I "
    }

    chain OUTPUT {
        type filter hook output priority filter; policy drop;
# not tracked. no conntracking
        oifname "eth0" udp sport 51820 accept
        ct state established accept
        ct state related accept
        jump output_filter
        log prefix "O " flags skuid
    }

    chain forward_filter {
        iifname "wg" oifname "wg" tcp dport 443 ct state new accept
        iifname "wg" oifname "wg" tcp dport 8123 ct state new accept
        iifname "wg" oifname "eth0" icmp type echo-request ct state new accept
    }

    chain input_filter {
        iifname "lo" ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept
        iifname "eth0" ip saddr 10.0.2.2 ip daddr 10.0.2.15 tcp dport 22 ct state new accept
        iifname "eth0" tcp dport 25 ct state new accept
        iifname "wg" tcp dport 22 ct state new accept
        iifname "wg" udp dport 5053 ct state new accept
        iifname "wg" tcp dport 5053 ct state new accept
        iifname "wg" tcp dport 9050 ct state new accept
        iifname "wg" icmp type echo-request ct state new accept
        iifname "eth0" udp sport 68 udp dport 67 ip saddr 0.0.0.0 ip daddr 255.255.255.255 accept
    }

    chain output_filter {
        oifname "lo" ct state new accept
        meta skuid 0 ct state new accept
        meta skuid nsd oifname "wg" tcp dport 5053 ct state new accept
        meta skuid nsd oifname "wg" udp dport 5053 ct state new accept
    }

    chain protos_check {
        ct state invalid drop
        icmp type echo-request meta length 85-65535 drop
        ip frag-off & 8191 != 0 drop
        ip protocol tcp return
        ip protocol icmp return
        ip protocol udp return
        log prefix "P "
        drop
    }

    chain divert {
        type filter hook prerouting priority mangle; policy accept;
        meta l4proto tcp socket transparent 1 meta mark set 0x00000001 accept
    }
}

table ip mangle {
    chain OUTPUT {
        type route hook output priority mangle; policy accept;
        tcp flags syn / syn,rst tcp option maxseg size set rt mtu
        meta mark set ct mark
        meta mark != 0x00000000 accept
    }

    chain FORWARD {
        type filter hook forward priority mangle; policy accept;
        tcp flags syn / syn,rst tcp option maxseg size set rt mtu
    }

    chain PREROUTING {
        type filter hook prerouting priority mangle; policy accept;
        meta mark set ct mark
        meta mark != 0x00000000 accept
    }
}

table ip nat {
    chain POSTROUTING {
        type nat hook postrouting priority srcnat; policy accept;
        oifname "eth0" masquerade
    }

    chain PREROUTING {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "wg" ip daddr 9.9.9.9 udp dport 123 numgen inc mod 1 0 dnat to 127.0.0.1:123 fully-random
    }
}

table ip raw {
    chain PREROUTING {
        type filter hook prerouting priority raw; policy accept;
        iifname "eth0" udp dport 51820 notrack
    }

    chain OUTPUT {
        type filter hook output priority raw; policy accept;
        oifname "eth0" udp dport 51820 notrack
    }
}

table ip6 filter {
    chain FORWARD {
        type filter hook forward priority filter; policy drop;
    }

    chain INPUT {
        type filter hook input priority filter; policy drop;
    }

    chain OUTPUT {
        type filter hook output priority filter; policy drop;
    }
}
